// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD1Pj6x-MdzRjl_hTsdUMjbKPRa6RHSUY',
    appId: '1:996024686957:web:b3d372e6f2a343943ba264',
    messagingSenderId: '996024686957',
    projectId: 'finalprojectbootcamp-86f5c',
    authDomain: 'finalprojectbootcamp-86f5c.firebaseapp.com',
    storageBucket: 'finalprojectbootcamp-86f5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeICQBxbaEJGPFx823ULLjiawcXGR0YAM',
    appId: '1:996024686957:android:c39e482104dd937b3ba264',
    messagingSenderId: '996024686957',
    projectId: 'finalprojectbootcamp-86f5c',
    storageBucket: 'finalprojectbootcamp-86f5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgCO1PrQ2tSZRSPYjJL1yz7Ai7p4Ys-r4',
    appId: '1:996024686957:ios:275bc9b929d6c18d3ba264',
    messagingSenderId: '996024686957',
    projectId: 'finalprojectbootcamp-86f5c',
    storageBucket: 'finalprojectbootcamp-86f5c.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgCO1PrQ2tSZRSPYjJL1yz7Ai7p4Ys-r4',
    appId: '1:996024686957:ios:275bc9b929d6c18d3ba264',
    messagingSenderId: '996024686957',
    projectId: 'finalprojectbootcamp-86f5c',
    storageBucket: 'finalprojectbootcamp-86f5c.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD1Pj6x-MdzRjl_hTsdUMjbKPRa6RHSUY',
    appId: '1:996024686957:web:9f9e5ff8ec219ba23ba264',
    messagingSenderId: '996024686957',
    projectId: 'finalprojectbootcamp-86f5c',
    authDomain: 'finalprojectbootcamp-86f5c.firebaseapp.com',
    storageBucket: 'finalprojectbootcamp-86f5c.appspot.com',
  );
}
